name: sccache Benchmark (Avrea)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: avrea-ubuntu-latest-8-vcpu
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup show

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Configure sccache
        run: echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Build risingwave_common
        run: |
          time cargo build -p risingwave_common
          sccache --show-stats
